- _Name: "Logitech Wireless Mouse"
  _ProductID: "E421"
  _Price: 10.99
  _Quantity: 53

- _Name: "Hanes XL - Navy Blue Pullover - 80% Cotton; 20% Polyester"
  _ProductID: "P452"
  _Price: 19.99
  _Quantity: 20

- _Name: "The One Ring"
  _ProductID: "T1R!"
  _Price: 10.00
  _Quantity: 1